### PR TITLE
Fix group deletion acceptance tests (work-around)

### PR DESCRIPTION
**Pull request by pdecat**
Fix for upstream PR: https://github.com/terraform-providers/terraform-provider-gitlab/pull/58

### CODE REVIEW

**Comment by matejvelikonja** [comment]
I think you should use `StateChangeConf` instead of `sleep` here

https://godoc.org/github.com/hashicorp/terraform/helper/resource#StateChangeConf

**Comment by pdecat** [comment]
Certainly, that's just a work-around to make the test pass and unblock [terraform-providers#58](https://github.com/terraform-providers/terraform-provider-gitlab/pull/58).

`StateChangeConf` should be used in the actual implementation of the resource, not the tests.

**Comment by roidelapluie** [comment]
we should do something like

```
	stateConf := &resource.StateChangeConf{
		Pending: []string{"Deleting"},
		Target:  []string{"Deleted"},
		Refresh: func() (interface{}, string, error) {
			out, response, err := client.Projects.GetProject(d.Id())
			if err != nil {
				if response.StatusCode == 404 {
					return out, "Deleted", nil
				}
				log.Printf("[ERROR] Received error: %#v", err)
				return out, "Error", err
			}
			return out, "Deleting", nil
		},

		Timeout:    10 * time.Minute,
		MinTimeout: 3 * time.Second,
		Delay:      5 * time.Second,
	}
```

**Comment by pdecat** [comment]
No longer needed :)

**Pull request closed without merging**
